version: '3.3'

services:
  AEYE-Router:
    image: aeye_web_router:1.0
    container_name: router_container
    build:
      context: ..
      dockerfile: Docker/Network_Router/Dockerfile
    ports:
    - "2000:2000"
    volumes:  
    - ../AEYE_Router/:/app/AEYE_Router
    networks:
      - aeye_network
    command: python manage.py runserver 0.0.0.0:2000
    
networks:
  aeye_network:
    driver: bridge
